name: CD

on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          registry-url: https://registry.npmjs.org/

      - name: Update Version in package.json
        run: sed -i 's/X.X.X/${{ github.event.release.tag_name }}/g' ./package.json

      - name: Install Dependencies
        run: npm install

      - name: Build TypeScript
        run: npm run build

      - run: npm publish --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
