name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Move into src directory
        run: cd src

      - name: Update Version in package.json
        run: sed -i 's/X.X.X/0.0.1/g' ./package.json

      - name: Install Dependencies
        run: npm install

      - name: Lint Source
        run: npm run lint

      - name: Build TypeScript
        run: npm run build
